CI18-56 & CI18-77 - Searching Loan and Savings transactions
fiterafrica/fineract-template pull request #109
Opened 2023-04-06 09:53 UTC by jumba2010

## Description

This PR covers two tickets (CI18-56 and CI18-77). The objective is to allow user to search loan and savings transaction by utilizing different criterias

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [ ] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/legacy-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

2023-04-06 10:54 UTC, hagafrank approved these changes, later dismissed

2023-04-12 04:44 UTC, hero78 requested changes
@jumba2010  We Expect Integration Tests on all PRs getting into Single Repo. Please Add Karate Test

2023-04-19 22:40 UTC, jumba2010 commented
@hero78 , the karate tests have been added. Please approve the PR

2023-04-24 07:04 UTC, hero78 approved these changes
LGTM

2023-04-24 07:04 UTC, hero78 commented on fineract-provider/src/main/resources/db/changelog/tenant/changelog-tenant.xml
> +<!--    <include file="parts/0026_reversals_for_reversed_transactions.xml" relativeToChangelogFile="true"/>-->
Why is this changeset commented out ?

2023-04-24 07:05 UTC, hagafrank commented on fineract-provider/src/main/resources/db/changelog/tenant/changelog-tenant.xml
> +<!--    <include file="parts/0026_reversals_for_reversed_transactions.xml" relativeToChangelogFile="true"/>-->
@jumba2010 please answer this

2023-04-24 07:07 UTC, hagafrank approved these changes

2023-04-24 07:07 UTC, merged