CI18-92 - Undo Loan Reschedule
fiterafrica/fineract-template pull request #128
Opened 2023-04-28 06:45 UTC by jumba2010

## Description

This PR is to allow undo of Loan Reschedule

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [ ] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/legacy-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

2023-05-03 08:23 UTC, MageziArthur submitted a review, later dismissed

2023-05-03 14:04 UTC, hero78 approved these changes, later dismissed

2023-05-03 14:17 UTC, Deepika1095 approved these changes, later dismissed

2023-05-03 14:41 UTC, jumba2010 commented
Hi @Deepika1095  and @hero78 , kindly reapprove the PR. It had some merge conflicts which I had to fix

2023-05-04 07:32 UTC, hero78 approved these changes

2023-05-04 08:19 UTC, MageziArthur requested changes
This test is not testing schedules after a reschedule. Apart from the post API i'd want to see the impact of the undo schedule on the original schedule.

Look out for the loan terms, first instalment date and last instalment dates. This test should reflect that

2023-05-04 08:19 UTC, MageziArthur commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/loanaccount/rescheduleloan/service/LoanRescheduleRequestWritePlatformServiceImpl.java
> +            loanRescheduleRequests.stream()
I really hoped for you to recall the abstract schedule generator to regenerate the schedule afressh after undoing a reschedule.

2023-05-09 05:01 UTC, closed without merging