Carbon ci18 60 create task
fiterafrica/fineract-template pull request #139
Opened 2023-05-08 18:52 UTC by BrianMuhimbura

## Create Tasks

Create, Update, Tasks

2023-05-08 19:23 UTC, hagafrank requested changes
Please remove the commented-out code

2023-05-08 19:23 UTC, hagafrank commented on fineract-provider/src/main/java/org/apache/fineract/organisation/tasks/api/TasksApiResource.java
> +    // private final CodeValueReadPlatformService codeValueReadPlatformService;
Please remove this

2023-05-08 19:23 UTC, hagafrank commented on fineract-provider/src/main/java/org/apache/fineract/organisation/tasks/api/TasksApiResource.java
> +            // this.codeValueReadPlatformService.retrieveCodeValuesByCode("taskStatus");
This is a new class but you have commented-out code. Do you plan to make use of this later?

2023-05-09 07:55 UTC, hagafrank approved these changes, later dismissed

2023-05-09 08:07 UTC, jumba2010 requested changes

2023-05-09 08:07 UTC, jumba2010 commented on fineract-provider/src/main/java/org/apache/fineract/organisation/tasks/domain/TaskRepositoryWrapper.java
> +}
Do you really need to have this Wrapper class? Having so many beans can slow down application startup

2023-05-09 08:07 UTC, jumba2010 commented on fineract-provider/src/main/resources/db/changelog/tenant/changelog-tenant.xml
> +    <include file="parts/CBN-CI18-143_create_tasks_and_permssions.xml" relativeToChangelogFile="true" />
Carbon migrations are placed in the custom_changelog folder and they start with CI18

2023-05-09 10:33 UTC, hagafrank approved these changes
LGTM

2023-05-09 10:41 UTC, jumba2010 approved these changes

2023-05-09 11:04 UTC, merged