OXY-260 failure to reschedule Loan Account.
fiterafrica/fineract-template pull request #192
Opened 2023-06-26 15:21 UTC by hero78

When rescheduling the Loan Account, New Repayment schedule is generated and old one is delete. So M_loan_repayment_reminder was blocking the operation since it had stored some loan account/s due to delete restriction

## Description

Describe the changes made and why they were made.

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [ ] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/legacy-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

2023-06-26 15:33 UTC, jumba2010 requested changes

2023-06-26 15:33 UTC, jumba2010 commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/loanaccount/rescheduleloan/service/LoanRescheduleRequestWritePlatformServiceImpl.java
> +        }
Because there is not any specific logic inside the for loop, I would suggest you use deleteAll or deleteInBatch methods instead of deleting one by one.  It is faster and takes less code.

2023-06-27 05:35 UTC, jumba2010 approved these changes
LGTM

2023-06-28 07:02 UTC, hagafrank approved these changes

2023-06-28 07:10 UTC, merged