INKO-46 - Managind Client household expenses
fiterafrica/fineract-template pull request #201
Opened 2023-07-07 14:51 UTC by jumba2010

## Description

Describe the changes made and why they were made.

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [ ] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/legacy-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

2023-07-10 07:51 UTC, hero78 requested changes

2023-07-10 07:51 UTC, hero78 commented on fineract-provider/src/main/resources/db/changelog/tenant/custom-changelog/INKO_046_HOUSEHOLD_EXPENSES.xml
> +            <column defaultValueComputed="NULL" name="createdby_id" type="BIGINT"/>
Make defaultValueComputed="now()" to set default value

2023-07-10 07:51 UTC, hero78 commented on karate-tests/src/test/resources/features/portfolio/clients/householdexpenses.feature
> +    * def otherExpensesTypeId = 24
Dynamicaly fetch this value instead of hard-coding.
Reason being, It may not be the same on all machines. This will cause this test to fail

2023-07-10 07:51 UTC, hero78 commented on karate-tests/src/test/resources/features/portfolio/clients/householdexpenses.feature
> +
Add one test to run when config has is disabled

2023-07-10 07:51 UTC, hero78 commented on karate-tests/src/test/resources/features/portfolio/clients/householdexpenses.feature
> +
@jumba2010  After this test disable the configuration so that other tests don't fail incase they depend on this data

2023-07-12 05:11 UTC, hero78 requested changes

2023-07-12 05:11 UTC, hero78 commented on fineract-provider/src/main/java/org/apache/fineract/commands/service/CommandWrapperBuilder.java
> +        this.href = "/householdexpenses/" + clientId;
Is this intentional [this.href = "/householdexpenses/" + clientId;] or meant to [householdExpenseId]

2023-07-12 06:51 UTC, hero78 approved these changes
LGTM

2023-07-12 07:28 UTC, Deepika1095 approved these changes

2023-07-12 07:31 UTC, merged