API's to add more information for companies (entity) clients
fiterafrica/fineract-template pull request #211
Opened 2023-07-12 12:19 UTC by Deepika1095

https://fiterio.atlassian.net/browse/INKO-61

## Description

Describe the changes made and why they were made.

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [ ] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/legacy-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

2023-07-12 12:50 UTC, jumba2010 submitted a review, later dismissed

2023-07-12 13:02 UTC, hero78 requested changes

2023-07-12 13:02 UTC, hero78 commented on fineract-provider/src/main/resources/db/changelog/tenant/custom-changelog/inko_61_add_column_for_client_other_info_company.xml
> +        <dropNotNullConstraint
add pre-condition to check if coumn exists before dropping this constraint

2023-07-12 13:02 UTC, hero78 commented on fineract-provider/src/main/resources/db/changelog/tenant/custom-changelog/inko_61_add_column_for_client_other_info_company.xml
> +        <dropNotNullConstraint
same thing here too

2023-07-13 06:47 UTC, Deepika1095 commented on fineract-provider/src/main/resources/db/changelog/tenant/custom-changelog/inko_61_add_column_for_client_other_info_company.xml
> +        <dropNotNullConstraint
fixed

2023-07-13 06:47 UTC, Deepika1095 commented on fineract-provider/src/main/resources/db/changelog/tenant/custom-changelog/inko_61_add_column_for_client_other_info_company.xml
> +        <dropNotNullConstraint
Fixed

2023-07-13 08:02 UTC, hero78 approved these changes

2023-07-13 12:30 UTC, jumba2010 approved these changes

2023-07-13 12:30 UTC, merged