INKO-240 : API Implementation to Move Loan from Pending Disbursement to Active
fiterafrica/fineract-template pull request #459
Opened 2023-12-10 15:40 UTC by tabrez-fiter

## Description

Describe the changes made and why they were made.

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [ ] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/legacy-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

2023-12-11 07:04 UTC, hagafrank requested changes
Please remove sensitive information from docker-compose

2023-12-11 07:04 UTC, hagafrank commented on docker-compose.yml
> +      - INKOMOKO_REST_INITIATE_DISBURSEMENT=https://41.242.142.227:6093/inkomoko-integrations/api/v1/disbursement/initiate
We normally discourage putting sensitive information in the repository. Can you instead use localhost and test credentials, then pass these as environment variables or GitHub secrets at deployment time?

2023-12-11 11:13 UTC, BrianMuhimbura approved these changes

2023-12-12 07:17 UTC, hagafrank approved these changes

2023-12-12 08:03 UTC, merged