CI18-142- Fixing migration issues
fiterafrica/fineract-template pull request #95
Opened 2023-03-29 13:53 UTC by jumba2010

## Description

Describe the changes made and why they were made.

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [ ] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/legacy-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

2023-03-29 13:59 UTC, hiteshprajapati approved these changes, later dismissed

2023-03-29 17:06 UTC, hagafrank requested changes
@jumba2010 what's the purpose of this PR? What are the migration issues? Have you tested this on an existing database?

Also, can you move the new migrations to `resources/db/changelog/custom-changelog` and then remove lines 85 and 86 from `resources/db/changelog/tenant/changelog-tenant.xml`

2023-03-30 07:39 UTC, hagafrank approved these changes

2023-03-30 12:45 UTC, hiteshprajapati approved these changes

2023-03-30 13:12 UTC, merged